### PR TITLE
Optmized the code comments.

### PR DESCRIPTION
**Pull request by cxcxyking**
I find your code have not been comment fully and correctly, so I was fixed them and created this PR. 👍

### CODE REVIEW

**Comment by idawnlight** [comment]
@xtlsoft I think XPHP **shouldn't** support PHP 5.4 anymore, which is already outdated.

**Comment by xtlsoft** [comment]
Wait and I'll check the compatiblity.

**Comment by xtlsoft** [comment]
The code style is different, so I'll make some changes before merging.

**Comment by cxcxyking** [comment]
So... after many years, this merge request still not be handled

**Pull request closed without merging**
